name: Deploy to Github Pages

on:
  push:
    branches: ['main','develop']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
    
    - name: Build Application
      run: dotnet publish -c Release ./src/ReturnNotFound/ReturnNotFound.csproj

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
           github_token: ${{ secrets.PUBLISH_TOKEN }}
           publish_dir: ./ReturnNotFound/bin/Release/net8.0/publish/wwwroot/
           

